title: color codes
email: koukun0120@gmail.com
description: >-
  color codes
baseurl: ""
url: "color-code-images.github.io"
twitter_username: yamadashy
github_username:  yamadashy

includes_dir: _images

collections:
  images:
    output: true
    permalink: /16/:name

exclude:
  - README.md
